### ISSUE TITLE
Table creation fails if fillable = Yes and table is fully qualified

### ISSUE THREAD

**Issue by Martleby** [Power-Components/powergrid-doc#12]
Hi,

In my User model I have: 

`protected $table = 'focus.dbo.users';` //fully qualified table name

(This is a SQL Server database - and my app actually uses three different databases and so I have to fully qualify to do cross-database queries).

When I run through the table creation wizard (php artisan powergrid:create) and if I say Yes to the fillable option I get an error:

`There is no column with name 'id' on table 'dbo'.` And indeed there isn't because there is no table named 'dbo'.

Cheers,
Martin.

**Comment by dansysanalyst** [comment]
Please open your issue in the correct repository. Thank you!

## Support

For questions, issues, bug reports and feature requests, please use [PowerGrid](https://github.com/Power-Components/livewire-powergrid) official GitHub Repository.

Please look into our previous issues to verify if your bug/question or feature request has been previously submitted.

📣 Submit a [new issue](https://github.com/Power-Components/livewire-powergrid/issues).

<br/>
