### ISSUE TITLE
Loading Data

### ISSUE THREAD

**Issue by abbasmashaddy72** [Power-Components/powergrid-doc#4]
Hi!

@dansysanalyst @luanfreitasdev 

Your package is very Good and working without any issues, but I think it will be good to add a loading spinner in the middle of the table till the data is loaded completely, as it is taking some time to load 500 records of data with relationship.

If you need to take the look at the integration I had made, you can look into the repo link: [GitHub Repo](https://github.com/abbasmashaddy72/new_blade_common)

You can follow the steps of Laravel with seeder as dummy data is already inserted.

You can check the [Polices URL](http://127.0.0.1:8000/policies) after login and seeding the data.

**Comment by dansysanalyst** [comment]
Please open your issue in the correct repository. Thank you!

## Support

For questions, issues, bug reports and feature requests, please use [PowerGrid](https://github.com/Power-Components/livewire-powergrid) official GitHub Repository.

Please look into our previous issues to verify if your bug/question or feature request has been previously submitted.

📣 Submit a [new issue](https://github.com/Power-Components/livewire-powergrid/issues).

<br/>
