### ISSUE TITLE
Not Working with eloquent relation( eager loading)

### ISSUE THREAD

**Issue by rakrisi** [Power-Components/powergrid-doc#5]
I try this 
 public function datasource(): ?Builder
    {
        return state::query()->with('country');
       
    }

for display data i use

Column::add()
                ->title(__('COUNTRY'))
                ->field('******')
                ->makeInputRange(),

what i have to write in field section if i have to print the country of the state ..

after doing over engineering i get the full array of country row.

not able to get country name ...

**Comment by luanfreitasdev** [comment]
Hi, can you take a look at our repo demo? There's something similar there with Dishes and Categories.

**Comment by rakrisi** [comment]
ya, i look into it ... 
its working fine with join quary 

but when i used eager loading
state::query()->with('country');

its gives the full array of country row  on 
->field('country')
{"id":70,"name":"Ethiopia","latitude":"8.00000000","longitude":"38.00000000","created_at":"2018-07-21T01:41:03.000000Z","updated_at":"2021-11-06T16:34:54.000000Z","flag":1}

and when i used 
->field('country.name')

or 
->field('country()->name')

its gives nothing

**Comment by devsquad-luan-freitas** [comment]
can you post the component class?

**Comment by rakrisi** [comment]
<?php

namespace App\Http\Livewire;

use App\models\state;
use Illuminate\Support\Carbon;
use Illuminate\Database\QueryException;
use Illuminate\Database\Eloquent\Builder;
use PowerComponents\LivewirePowerGrid\Button;
use PowerComponents\LivewirePowerGrid\Column;
use PowerComponents\LivewirePowerGrid\PowerGrid;
use PowerComponents\LivewirePowerGrid\PowerGridEloquent;
use PowerComponents\LivewirePowerGrid\PowerGridComponent;
use PowerComponents\LivewirePowerGrid\Traits\ActionButton;

class stateTable extends PowerGridComponent
{
    use ActionButton;

    /*
    |--------------------------------------------------------------------------
    |  Features Setup
    |--------------------------------------------------------------------------
    | Setup Table's general features
    |
    */
    public function setUp()
    {
        $this->showCheckBox()
            ->showPerPage()
            ->showExportOption('download', ['excel', 'csv'])
            ->showSearchInput();
    }

    /*
    |--------------------------------------------------------------------------
    |  Datasource
    |--------------------------------------------------------------------------
    | Provides data to your Table using a Model or Collection
    |
    */
    public function datasource(): ?Builder
    {
        return state::query()->with('country');


    }

    /*
    |--------------------------------------------------------------------------
    |  Relationship Search
    |--------------------------------------------------------------------------
    | Configure here relationships to be used by the Search and Table Filters.
    |
    */
    public function relationSearch(): array
    {
        return [];
    }

    /*
    |--------------------------------------------------------------------------
    |  Add Column
    |--------------------------------------------------------------------------
    | Make Datasource fields available to be used as columns.
    | You can pass a closure to transform/modify the data.
    |
    */
    public function addColumns(): ?PowerGridEloquent
    {
        return PowerGrid::eloquent()
            ->addColumn('id')
            ->addColumn('name')
            ->addColumn('country')
            ->addColumn('latitude')
            ->addColumn('longitude')
            ->addColumn('flag')
            ->addColumn('created_at_formatted', function(state $model) {
                return Carbon::parse($model->created_at)->format('d/m/Y H:i:s');
            })
            ->addColumn('updated_at_formatted', function(state $model) {
                return Carbon::parse($model->updated_at)->format('d/m/Y H:i:s');
            });
    }

    /*
    |--------------------------------------------------------------------------
    |  Include Columns
    |--------------------------------------------------------------------------
    | Include the columns added columns, making them visible on the Table.
    | Each column can be configured with properties, filters, actions...
    |
    */
    public function columns(): array
    {
        return [
            Column::add()
                ->title(__('ID'))
                ->field('id')
                ->makeInputRange(),

            Column::add()
                ->title(__('NAME'))
                ->field('name')
                ->sortable()
                ->searchable()
                ->makeInputText(),

            Column::add()
                ->title(__('COUNTRY'))
                ->field('country')
                ->makeInputRange(),

            Column::add()
                ->title(__('LATITUDE'))
                ->field('latitude')
                ->sortable()
                ->searchable(),

            Column::add()
                ->title(__('LONGITUDE'))
                ->field('longitude')
                ->sortable()
                ->searchable(),

            Column::add()
                ->title(__('FLAG'))
                ->field('flag')
                ->toggleable(),

            Column::add()
                ->title(__('CREATED AT'))
                ->field('created_at_formatted')
                ->searchable()
                ->sortable()
                ->makeInputDatePicker('created_at'),

            Column::add()
                ->title(__('UPDATED AT'))
                ->field('updated_at_formatted')
                ->searchable()
                ->sortable()
                ->makeInputDatePicker('updated_at'),

        ]
;
    }

    /*
    |--------------------------------------------------------------------------
    | Actions Method
    |--------------------------------------------------------------------------
    | Enable this section only when you have defined routes for these actions.
    |
    */

    /*
    public function actions(): array
    {
       return [
           Button::add('edit')
               ->caption(__('Edit'))
               ->class('bg-indigo-500 text-white')
               ->route('state.edit', ['state' => 'id']),

           Button::add('destroy')
               ->caption(__('Delete'))
               ->class('bg-red-500 text-white')
               ->route('state.destroy', ['state' => 'id'])
               ->method('delete')
        ];
    }
    */

    /*
    |--------------------------------------------------------------------------
    | Edit Method
    |--------------------------------------------------------------------------
    | Enable this section to use editOnClick() or toggleable() methods
    |
    */


    public function update(array $data ): bool
    {
       try {
           $updated = state::query()->find($data['id'])->update([
                $data['field'] => $data['value']
           ]);
       } catch (QueryException $exception) {
           $updated = false;
       }
       return $updated;
    }

    public function updateMessages(string $status, string $field = '_default_message'): string
    {
        $updateMessages = [
            'success'   => [
                '_default_message' => __('Data has been updated successfully!'),
                //'custom_field' => __('Custom Field updated successfully!'),
            ],
            'error' => [
                '_default_message' => __('Error updating the data.'),
                //'custom_field' => __('Error updating custom field.'),
            ]
        ];

        return ($updateMessages[$status][$field] ?? $updateMessages[$status]['_default_message']);
    }


    public function template(): ?string
    {
        return null;
    }

}



model:


<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class state extends Model
{
    use HasFactory;
    protected $fillable = [
        'name',
        'country_id',
        'latitude',
        'longitude',
        'flag'
    ];
    public function country()
    {
        return $this->belongsTo(Country::class);
    }
}

**Comment by clickanidea** [comment]
```php
 public function addColumns(): ?PowerGridEloquent
{
    return PowerGrid::eloquent()
        ->addColumn('id')
        ->addColumn('name')
        ->addColumn('country', function (State $model) {
                return $model->country->name;
        })
        ->addColumn('latitude')
        ->addColumn('longitude')
        ->addColumn('flag')
        ->addColumn('created_at_formatted', function(state $model) {
            return Carbon::parse($model->created_at)->format('d/m/Y H:i:s');
        })
        ->addColumn('updated_at_formatted', function(state $model) {
            return Carbon::parse($model->updated_at)->format('d/m/Y H:i:s');
        });
}
```
Are you sure it's `country` and not `country_id` ?
Than in columns :
```php
Column::add()
            ->title(__('COUNTRY'))
            ->field('country') // or country_id, whatever is in your database table 
            ->makeInputRange(),
```
It works perfectly for me in belongsTo relations

**Comment by luanfreitasdev** [comment]
Thanks @clickanidea

**Comment by rakrisi** [comment]
Thanks @clickanidea  
Now It's Working.
